name: Deploy to Staging

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Package Theme
      run: |
        mkdir -p dist/docy
        rsync -a --exclude='dist' --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='.ftp-deploy-sync-state.json' . dist/docy/
      
    - name: FTP Deploy to Staging
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local-dir: ./dist/docy/
        server-dir: wp-content/themes/docy/
        state-name: .ftp-deploy-sync-state-force.json
